import Typography from "@mui/material/Typography";
import type { Metadata } from "next";
import { DocumentSection, DraftLegalNotice, InformationPage } from "@/components/information/information-page";
import { NOINDEX_FOLLOW, createPageMetadata } from "@/lib/seo/metadata";

export const metadata: Metadata = createPageMetadata({ title: "Privacy Policy", description: "Draft privacy information for SL Furnitures.", canonicalPath: "/privacy-policy", robots: NOINDEX_FOLLOW });

export default function PrivacyPolicyPage() {
  return <InformationPage title="Privacy Policy" introduction="How the current website handles information you choose to provide."><DraftLegalNotice /><DocumentSection title="Information we handle"><Typography>When you contact us or submit a furniture request, the website can collect the name, phone number or email address, and message you provide. Optional reference attachments are kept private. Customer accounts are authenticated by Clerk, while the application maintains a local customer profile for authorized services.</Typography></DocumentSection><DocumentSection title="How information is used"><Typography>Information submitted through enquiries and furniture requests is used to review and respond to that submission. Authenticated account information is used to identify the account for services that require it. The application also retains operational records needed to provide its current features.</Typography></DocumentSection><DocumentSection title="Service providers and security"><Typography>Clerk provides authentication services. The website and Laravel API apply request validation, authorization, rate limits, and private attachment access controls. No policy approval has yet been recorded for analytics, advertising, messaging, international transfers, or other third-party data processing.</Typography></DocumentSection><DocumentSection title="Retention and your choices"><Typography>Retention periods, deletion procedures, privacy rights, and a privacy contact channel have not yet been approved. These decisions must be added during legal and business review before this policy is finalized.</Typography></DocumentSection><DocumentSection title="Policy updates"><Typography>Any approved privacy policy will state its effective date and how material updates are communicated.</Typography></DocumentSection></InformationPage>;
}
